# Generated by Django 4.0.2 on 2022-02-10 13:35

import DjangoApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='temps_allocated',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10, 'Minimum time = 10')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, validators=[DjangoApp.models.is_Esprit_Email]),
        ),
    ]
