# Generated by Django 4.0.2 on 2022-02-10 13:50

import DjangoApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0002_alter_projet_temps_allocated_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, validators=[DjangoApp.models.is_Esprit_Email], verbose_name='Email'),
        ),
    ]
